name: deno-deployment

on:
  pull_request:
    branches: [master]
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "deno-image"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker run -d --name deno-container "${IMAGE_NAME}"

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push if pull request
        uses: docker/build-push-action@v4
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
        with:
          push: true
          context: ./
          tags: ${{ secrets.DOCKERHUB_USER }}/deno_docker:latest

  continuous-delivery:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    needs: [ci]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push if tag create
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          tags: ${{ secrets.DOCKERHUB_USER }}/deno_docker:${{ github.ref_name }}      